### ISSUE TITLE
Error with product_pack and "detailed" options

### ISSUE THREAD

**Issue by antoniocanovas** [ingadhoc/product#11]
Hello, I am receiving this error in a clean instance updated  yesterday:

<img width="595" alt="captura de pantalla 2016-04-18 a las 14 08 24" src="https://cloud.githubusercontent.com/assets/8323017/14603614/1549a23e-056f-11e6-965e-748983f3f9c1.png">

ValidateError
Error while validating constraint
get_sale_order_line_vals() takes exactly 5 arguments (3 given) 

Am I doing anything wrong?
Thank you.

**Comment by jjscarafia** [comment]
Strange.. can you try to replicat in our runbot and specified steps to reproduce it?
http://runbot.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-product-git-28
Thanks!

**Comment by antoniocanovas** [comment]
Gracias al acceso que me has dado he podido comprobar que estaba utilizando
el módulo de tu repositorio "odoo-addons" que no está actualizado (v2.2).

Procedo a probar el que hay en "product" (v3.3).

Muchas gracias por tu respuesta Juan José.

Un saludo,

---

```
   Antonio Cánovas Pedreño
```

antonio.canovas@ingenieriacloud.com
         Teléfono.- 6224.2.6224
-         Twitter.- @acanovasp http://www.twitter.es/acanovasp*

2016-04-18 15:18 GMT+02:00 Juan José Scarafía notifications@github.com:

> Strange.. can you try to replicat in our runbot and specified steps to
> reproduce it?
> 
> http://runbot.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-product-git-28
> Thanks!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ingadhoc/product/issues/11#issuecomment-211375909

## 

 http://www.konery.es
Antes de imprimir este e-mail piense bien si es necesario, la conservación 
del medio ambiente es tarea de todos.
Este mensaje contiene información CONFIDENCIAL sometida a secreto 
profesional. Si lo ha recibido por error, debe saber que la copia, uso o 
divulgación están prohibidos la Ley, por ello, le rogamos que nos lo 
comunique por esta misma vía y proceda a su destrucción. 

Muchas gracias.
