### ISSUE TITLE
product_sale_uom

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/product#120]
Hola @jjscarafia,

Quisiera proponer algunos cambios a este módulo/s, pero antes de hacerlo me gustaría conocer tu opinión.

**Separarlo en varios módulos** 
`product_uoms`: Base para todos los otros. Define las distintas `uoms` del producto.
`product_uoms_sale`: Glue para usar domains en sale. Agrega boolean `sale_ok` a cada uom.
`product_uoms_stock`: Glue para usar domains en stock. Agrega boolean `stock_ok` a cada uom.
`product_uoms_purchase`: Glue para usar domains en purchase. Agrega boolean `purchase_ok` a cada uom.

De esa manera, se podrían especificar multiples unidades de medida, y definir en dónde es posible usarlas.

**Uso de constrains**
En cada glue module, usar constrains además de actualizar el domain con los onchange. Nos ha pasado que por problemas de actualización de las vista se terminaron validando sale.orders con unidades de medida incorrecta. Con esto se solucionaría, creo.

**Campos extra**
En el modulo base, agregaría campos extra. Nos interesa agregar, por ejemplo, un campo `ean` para cada `uom`, de cada variante. Se haría mediante one2many y campos calculados para que cada variante tenga su propia información extra. Sería visible desde `product.product`, pero no desde `product.template` (aunque se podría mostrar como one2many..)
Se podría evaluar agregar otros campos también.

Avisame si te parece bien, y si es viable hacerlo en `9.0`

**Comment by jjscarafia** [comment]
buenas Ivan,
mirá, justo estoy por inciar el repo de product en estos días. El cambio este la verdad que no sería tan sencillo.
Iría completamente sobre v11 con este cambio. Al fin y al cabo la idea es meterle pata y que los primeros que quieran puedan migrar en junio aprox.
Si te parece lo hacemos directamente sobre v11 y aprovechamos este issue para definir la idea y que hagas los PRs contra v11.

**Comment by jjscarafia** [comment]
Buenas Ivan,
Esto ya lo estaría trabajando nico en este PR https://github.com/ingadhoc/product/pull/171/files
Feedback bienvenido, por ahora la parte de stock no la haríamos ya que por lo que vemos no se puede elegir la uom en pickings (al menos en v11 y en lo que probamos hasta ahora).

Cualquier cosa nos decís.

Saludos,
Juan

**Comment by ivantodorovich** [comment]
Genial Juan!

Ahora lo reviso.
Muy raro lo de las uom en los pickings.. en la 9.0 nosotros lo usamos, más que nada porque el encargado de depósito se volvería loco si tuviera que interpretar la información basada en la unidad de medida base del producto!! ¿Seguro que lo sacaron?
