### ISSUE TITLE
Product Pack: Product quantity doens change when packed and soled in the POS

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/product#15]
in the module "product_pack" for a product pack, the sale in the POS doesn't change the available quantity for the pack and for the integrated products, it works only in sales orders

**Comment by mohamedhagag** [comment]
I've made this enhancement in a module

https://github.com/mohamedhagag/dvit-odoo8/tree/8.0/product_pack_pos

should we merge it with the parent module ?

**Comment by jjscarafia** [comment]
Hi! Thanks for the contributtion.
As I can see we should not merge them because we would force product_pack to depend on point_of_sale module.
If you want, you can make a PR suggesting to add your module to this repository. Have you tested on production? It works ok?
Thanks

**Comment by mohamedhagag** [comment]
We will provide it to our customer, and we are testing it with different scenarios now.

For sure we can make a PR to include it here in this repo.

**Comment by jjscarafia** [comment]
Thanks!
