### ISSUE TITLE
Problema con módulo Punto de venta (POS)

### ISSUE THREAD

**Issue by Maurix09** [ingadhoc/product#215]
Hoa, escribo desde Punta Alta, Bs. As. Argentina... Estoy probando el módulo "Product Currency" que permite tomar el precio de costo del producto en otra moneda que no sea la nativa de la empresa. Más precisamente, mi idea es tener los productos en dólares, y venderlos en pesos (por la conocida  variación del valor del dólar en nuestro país).

Uso "Tarifas" para calcular el precio de venta en pesos. TODO BIEN, cuando hago presupuestos o pedidos de venta, calcula bien el precio, pasando el valor del costo de dólares a pesos y luego aplicando el margen que yo haya colocado en "Tarifas"...

El problema aparece cuando utilizo el módulo Punto de Venta (POS) que viene con el Odoo 11.

Los precios que calcula el POS no son correctos. Calcula el margen de ganancia de la tarifa, pero toma al precio de costo de los productos, como si fueran en la moneda por defecto de la empresa.

Ejemplo:

Empresa LA PRUEBA, con moneda nativa PESOS ARGENTINOS
Activo la multi moneda  y pongo las tasas de las monedas.

Producto XXX: Precio de Costo = 100 (forzado a dólares)

Creo una TARIFA llamada "Precio de Lista" en donde digo que los productos tienen un 50% de utilidad sobre el precio de costo, y le digo que la tarifa es en PESOS ARGENTINOS.

Cuando creo un presupuesto o pedido de venta,,, al agregar una linea con el producto XXX, el sistema calcula al precio de venta como:

**Costo * 1,5 (margen) * Tasa ($ 46 por dólar) = 6900 pesos Argentinos...**

Eso es correcto!!!!

Pero si inicio una sesión en el módulo POS (poniendo que la TARIFAS "Precio de lista" es la por defecto).... Al iniciar la sesión, calcula al precio del producto XXX como:

**Costo * 1,5 = 150 pesos Argentinos....**

----------------------> Cual sería la solución al problema???

Muchas gracias.

**Comment by jjscarafia** [comment]
Buenas el modulo product_currency no cambia la moneda del precio de costo, solo la moneda del precio de venta.

Saludos!
