### ISSUE TITLE
Product_currency module is not showing changed currency in standard price due [Fix] committed in 25 Feb 

### ISSUE THREAD

**Issue by MohsenWaleed** [ingadhoc/product#223]
I found that there is one fix added into Odoo 11 to add a new field cost_currency_id to be used rather than currency_id as you can see in the below link:

https://github.com/odoo/odoo/commit/950d0f1849bebc20bfd6b2d71bedfd97d675b642#diff-92af3e72f90045de4a079550a2debc8b

When I installed product_currency module and change a product currency, the standard price currency not changed as you can see below:

![image](https://user-images.githubusercontent.com/24973578/61186141-9949b700-a66a-11e9-96bc-dcfbd86dcafe.png)

**Comment by jjscarafia** [comment]
HI, yes, actually product_currency, for now, does not affect standard price, only sale price.
Thanks!
