### ISSUE TITLE
Replenishment cost inconsistent

### ISSUE THREAD

**Issue by luismata01** [ingadhoc/product#378]
HI

After restore a database on production server module Replenishment Cost is inconsistent and show  this error on log.

odoo.addons.base.models.ir_model: Missing model product.replenishment_cost.rule

 odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['pos_default_customer', 'product_replenishment_cost', 'product_ux']

Can you help me please.

**Comment by jjscarafia** [comment]
Hi, that is not an issue related to the repo but to odoo installation and/or restore of database.
Sorry but we can't help on this with a simple suggestion.
