### ISSUE TITLE
Implementar mejoras de usabilidad a product_pack

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/product#79]
Mejoras propuestas aquí https://github.com/OCA/product-attribute/pull/118

**Comment by ovnicraft** [comment]
@jjscarafia para la migracion a la v10.0 se va a trabajar con el modulo de este repo o los cambios en el PR de referencia ?

**Comment by jjscarafia** [comment]
@ovnicraft la última versión del módulo, de la cual partiría, es la de este repo branch 9.0.
El PR a la oca es más viejo y no debe tener nada mejor que lo del branch 9.0

Pensabas trabajar el módulo para la v10? Yo todavía no creé los branch para no tener que andar sincronizando tantos branches, pensaba hacerlo en algunos meses. Pero si llegas a trabajar en este módulo, si te parece, cuando lo tengas mas o menos, avisame y lo creo.
Salvo que quieras aprovechas a tratar de llevarlo a la OCA. 

De trabajar en este módulo aprovecharía a tener en cuentas las mejoras propuestas de ese PR (y seguramente algunas otras mejoras)

**Comment by ovnicraft** [comment]
@jjscarafia prefiero trabajar sobre esta version y pasarlo a la version 10.0, adicional lo necesito de urgencia voy por un fork primero, me ayudas con la rama 10.0

**Comment by ovnicraft** [comment]
WIP: https://github.com/ovnicraft/product/tree/10.0-migration-product_pack
Con la rama 10.0 puedo hacer un PR y me ayudas con los reviews

**Comment by jjscarafia** [comment]
Done! Thanks @ovnicraft

**Comment by ovnicraft** [comment]
@jjscarafia Es posible una descripcion de la redefinicion realizada ? en la v9.0 ya que en la [10.0 addons/stock/models/product.py#L15](https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L115) se cambia el metodo y ya la old_api no esta disponible.

**Comment by jjscarafia** [comment]
perdón @ovnicraft pero no entiendo a que te referís. Veo que, como me indicas, migraron a la nueva api los métodos para cálculo de stock con "_compute_quantities_dict", perjudica en algo eso?

**Comment by ovnicraft** [comment]
Busco tu ayuda para entender el objetivo de redefinir las funciones que estan en la version 9.0.. asi con esto poder realizar el trabajo para la v10.
No perjudica, sin embargo segun tu aclaracion del por que se hizo de esa forma en la v9.0 ayudara a modificar el metodo en la v10

**Comment by jjscarafia** [comment]
Ahh, bárbaro, mirá, esto viene desde la 8 y dudo que lo hayamos cambiado cuando migramos a la 9. Según recuerdo y veo, la idea era que la disponibilidad y demás de los packs, este dado por la diposnibilidad de sus componentes. Por eso heredamos la función, llamamos a super para todo lo que no es pack y definimos [nuevo método](https://github.com/ingadhoc/product/blob/9.0/product_pack/models/product.py#L39) para los productos que son packs.
Se me ocurre que se debería hacer una implementación parecida pero imagino que no va a hacer falta redefinir los campos como hicimos [acá](https://github.com/ingadhoc/product/blob/9.0/product_pack/models/product.py#L73) que no recuerdo bien porque no funcionaba

**Comment by jjscarafia** [comment]
cierro ticket ya que este modulo se lleva ahora en la oca https://github.com/oca/product-pack
