### ISSUE TITLE
Product_pack Uncaught TypeError: Cannot read property '1' of undefined y cannot add taxes

### ISSUE THREAD

**Issue by isos** [ingadhoc/product#81]
Hello, after the installation of product_pack all the taxes are gone, also when I want to create a new product it give me the warning Uncaught TypeError: Cannot read property '1' of undefined and when I try to put a tax, the tax that I select disappear.

**Comment by isos** [comment]
Hello, after the installation of product_pack all the taxes are gone, also when I want to create a new product it give me the warning Uncaught TypeError: Cannot read property '1' of undefined and when I try to put a tax, the tax that I select disappear.

**Comment by jjscarafia** [comment]
Hi, can you please provide more information (version, steps to reproduce, etc). You can try this modules on our runbot (http://runbot.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-product-git-10). If error can't be reproduced on our runbot we won't fix it as we can't reproduce it.

You can check our guidelines to report issues here https://github.com/ingadhoc/odoo-argentina/wiki/Reporting-Issues

thanks

**Comment by isos** [comment]
Is was a mistake with other module, thanks
